apiVersion: v1
kind: Service
metadata:
   name: emqx-nodeport
   namespace: emqx
   labels:
      run: emqx
spec:
   selector:
      run: emqx
   type: NodePort
   ports:
   - name: mqtt
     port: 1883
     targetPort: 1883
     nodePort: 31884
     protocol: TCP
