apiVersion: v1
kind: Service
metadata:
   name: hivemq-nodeport
   namespace: hivemq
   labels:
      run: hivemq
spec:
   selector:
      run: hivemq
   type: NodePort
   ports:
   - name: mqtt
     port: 1883
     targetPort: 1883
     nodePort: 31885
     protocol: TCP
