apiVersion: v1
kind: Service
metadata:
   name: vernemq-nodeport
   namespace: vernemq
   labels:
      run: vernemq
spec:
   selector:
      run: vernemq
   type: NodePort
   ports:
   - name: mqtt
     port: 1883
     targetPort: 1883
     nodePort: 31886
     protocol: TCP
